version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
  redis:
    image: redis
    ports:
      - "6379:6379"
    container_name: redis